name: zresume
description: Make your free resume now!


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.18
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  responsive_framework: ^0.1.5
  pdf: ^3.6.5
  flutter_riverpod: ^2.5.1
  get: ^4.3.8
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  build_runner: ^2.0.4
  intl: ^0.19.0
  pdf_render: ^1.0.19
  printing: ^5.3.0
  universal_html: ^2.0.8

  google_fonts: ^6.2.1
  json_serializable: ^6.8.0
  adaptive_theme: ^3.6.0
  uuid: ^4.4.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  #flutterfire_ui: ^0.4.3+20
  google_sign_in: ^6.0.0
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true